openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Hello, World'
  description: 'hello world'
paths:
  /hello/world2/v0.0.1/welcome:
    post:
      description: Welcome.
      operationId: welcome
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: Bob
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcomeOutput'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    welcomeOutput:
      required:
        - result
      properties:
        result:
          type: string
          example: 'welcome'
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
