apiversion:
  in: query
  required: false
  name: v
  schema:
    type: string
genericresponse:
  type: object
  required:
    - result
  properties:
    result:
      type: object
genericerror:
  type: object
  required:
  - code
  - message
  properties:
    code:
      type: integer
      format: int32
    message:
      type: string
